### ISSUE TITLE
Cannot find shared object file

### ISSUE THREAD

**Issue by Avent37** [bungle/lua-resty-injection#1]
I'm trying to implement Libinjection in the Kong API through a plugin. I'm using resty.injection for the same but I'm running into the following error :

```

Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:57: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:576: /usr/local/share/lua/5.1/resty/injection.lua:13: libinjection.so: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:576: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/init.lua:103: in function 'load_plugins'
	/usr/local/share/lua/5.1/kong/init.lua:177: in function 'init'
	init_by_lua:3: in main chunk


  Run with --v (verbose) or --vv (debug) for more details
```
Please guide me on how to proceed further
This is my configuration
-Ubuntu 18.04
-Kong API 0.13.1
-Lua 5.1.5
-LuaJIT 2.1.0
-lua-resty-injection 1.0-1
-kong_injection plugin by @ror6ax

**Comment by bungle** [comment]
@TSK-37 do you have libinjection in your system library path?

**Comment by Avent37** [comment]
I completely missed the part of adding it in my system path. Thanks a lot!
